<template>
  <nuxt-layout name="admin">
    <div>
      <q-btn
        color="primary"
        label="Primary"
      />
      <QBtn
        color="secondary"
        label="Secondary"
      />
      <LazyQBtn
        color="amber"
        glossy
        label="Amber"
      />
    </div>
  </nuxt-layout>
</template>
